// Package tunnel — Named Cloudflare Tunnel supervisor.
//
// A "Named Tunnel" differs from a Quick Tunnel in three important ways:
//   - the public hostname is stable (e.g. forge.example.com), because it's
//     a CNAME in the user's Cloudflare zone — it does NOT rotate on each
//     process restart like *.trycloudflare.com
//   - it's driven by a config.yml + credentials.json pair on disk, not a
//     single --token flag
//   - it is intended to run forever, so this file adds a supervisor that
//     restarts cloudflared with exponential backoff and a restart-storm
//     guard rather than giving up on the first crash
//
// The supervisor emits HealthState transitions through a Ranker, which
// is how the frontend decides whether to show "Named Tunnel — Healthy"
// or "Named Tunnel — Degraded [Repair]".
package tunnel

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"io"
	"os/exec"
	"path/filepath"
	"sync"
	"time"
)

// NamedConfig is the minimum set of values the supervisor needs to
// start a Named Tunnel. Typically populated by the setup wizard and
// persisted to `~/.forge/tunnel/forge.yml`.
// JSON tags are lowercase so the /api/tunnel/setup/status payload matches
// what the frontend reads (`status.config.hostname`). Go's json.Unmarshal
// matches keys case-insensitively, so existing state.json files written
// before these tags existed (capitalized keys) still load cleanly — they
// will be rewritten with lowercase keys on the next SyncConfigPort or
// tunnel re-creation.
type NamedConfig struct {
	// TunnelUUID is the GUID assigned by Cloudflare when `cloudflared
	// tunnel create` succeeds. It identifies the tunnel and is embedded
	// in both the config.yml and the credentials JSON filename.
	TunnelUUID string `json:"tunnelUUID"`

	// Hostname is the public DNS record that CNAMEs to
	// <uuid>.cfargotunnel.com, e.g. "forge.example.com". This is the
	// value the mobile companion will use.
	Hostname string `json:"hostname"`

	// LocalPort is the loopback port cloudflared should forward to.
	// Always http://localhost:<port> — no HTTPS termination locally,
	// that's what the tunnel is for.
	LocalPort int `json:"localPort"`

	// ConfigPath is the absolute path to the cloudflared config.yml
	// generated by the setup wizard. The supervisor passes this with
	// --config so cloudflared uses our managed copy, not the user's.
	ConfigPath string `json:"configPath"`

	// CredentialsPath is the absolute path to <uuid>.json containing the
	// tunnel credentials. Validated on supervisor start; if the file is
	// missing the supervisor enters Degraded with a clear "log in again"
	// recovery hint.
	CredentialsPath string `json:"credentialsPath"`
}

// Supervisor manages the lifecycle of a single Named Tunnel.
//
// Design notes:
//   - Runs in its own goroutine (Start returns immediately)
//   - All state changes go through a Ranker, so UI reads are consistent
//   - Exponential backoff: 1s → 2s → 4s → 8s → 16s → 32s → 60s (capped)
//   - Restart-storm guard: if 5 consecutive crashes happen within 2
//     minutes, stop trying and enter StageStopped with "too many retries"
//   - Health probes run every 20s against `https://<hostname>/api/ping`;
//     3 consecutive failures demote Healthy → Degraded
type Supervisor struct {
	cfg      NamedConfig
	ranker   *Ranker
	bin      string        // path to cloudflared, resolved once at Start()
	probeURL string        // https://<hostname> — base for ProbeHTTP
	stopOnce sync.Once     // guards Stop()
	doneCh   chan struct{} // closed when the supervisor goroutine exits
	cancel   context.CancelFunc
}

// supervisorTiming collects the time-based knobs in one struct so tests
// can inject aggressive values without touching production defaults.
type supervisorTiming struct {
	initialBackoff   time.Duration
	maxBackoff       time.Duration
	probeInterval    time.Duration
	probeFailureMax  int           // consecutive failures before Degraded
	stormWindow      time.Duration // how far back we count crashes
	stormMaxCrashes  int           // crashes within window that trip the guard
	postStartGrace   time.Duration // grace period after spawn before first probe
	probeTimeoutEach time.Duration
}

func defaultTiming() supervisorTiming {
	return supervisorTiming{
		initialBackoff:   1 * time.Second,
		maxBackoff:       60 * time.Second,
		probeInterval:    20 * time.Second,
		probeFailureMax:  3,
		stormWindow:      2 * time.Minute,
		stormMaxCrashes:  5,
		postStartGrace:   5 * time.Second,
		probeTimeoutEach: 2 * time.Second,
	}
}

// NewSupervisor wires a NamedConfig to a Ranker. It does NOT start the
// cloudflared process — call Start to do that.
func NewSupervisor(cfg NamedConfig, ranker *Ranker) *Supervisor {
	return &Supervisor{
		cfg:      cfg,
		ranker:   ranker,
		probeURL: fmt.Sprintf("https://%s", cfg.Hostname),
		doneCh:   make(chan struct{}),
	}
}

// Start spawns the supervisor goroutine. Returns immediately; callers
// should use the Ranker to observe subsequent state transitions.
//
// If a blocking precondition fails (no cloudflared binary, no creds
// file) the supervisor immediately publishes Degraded with an
// actionable RecoveryHint and exits.
func (s *Supervisor) Start(ctx context.Context) {
	ctx, s.cancel = context.WithCancel(ctx)

	// Resolve cloudflared up front. If the binary is missing, publish
	// Absent + a hint pointing at the setup wizard's install step and
	// return before starting the goroutine.
	s.bin = ResolvePath()
	if s.bin == "" {
		s.ranker.Set(HealthState{
			Mode:         ModeIDNamed,
			Stage:        StageAbsent,
			RecoveryHint: "Install cloudflared",
			LastError:    "cloudflared binary not found on this system",
		})
		close(s.doneCh)
		return
	}

	// Validate the credentials file is readable. This is the most common
	// breakage ("I deleted ~/.cloudflared and didn't realise") so we
	// want a clear, specific error message rather than letting cloudflared
	// crash-loop with an opaque auth failure.
	if s.cfg.CredentialsPath == "" {
		s.ranker.Set(HealthState{
			Mode:         ModeIDNamed,
			Stage:        StageConfigured,
			RecoveryHint: "Complete tunnel setup",
			LastError:    "credentials path is empty — setup wizard not finished",
		})
		close(s.doneCh)
		return
	}

	go s.run(ctx, defaultTiming())
}

// Stop signals the supervisor to exit and waits for the cloudflared
// child (if any) to shut down cleanly. Idempotent.
func (s *Supervisor) Stop() {
	s.stopOnce.Do(func() {
		if s.cancel != nil {
			s.cancel()
		}
	})
	<-s.doneCh
}

// run is the supervisor loop. Each iteration:
//  1. publishes Starting
//  2. spawns cloudflared
//  3. waits for either child-exit OR probe-failure-threshold
//  4. classifies the outcome and either retries with backoff or aborts
//
// Extracted from Start to keep goroutine lifecycle testable.
func (s *Supervisor) run(ctx context.Context, timing supervisorTiming) {
	defer close(s.doneCh)

	backoff := timing.initialBackoff
	crashes := newCrashTracker(timing.stormWindow, timing.stormMaxCrashes)

	for {
		select {
		case <-ctx.Done():
			s.publish(StageStopped, "", "stopped by caller", "")
			return
		default:
		}

		s.publish(StageStarting, s.probeURL, "", "")

		exitErr := s.runOnce(ctx, timing)

		if errors.Is(exitErr, context.Canceled) {
			s.publish(StageStopped, "", "stopped by caller", "")
			return
		}

		crashes.record(time.Now())
		if crashes.stormTripped() {
			s.publish(StageStopped, "",
				fmt.Sprintf("cloudflared crashed %d times within %s — giving up; check logs and try 'Repair tunnel'",
					timing.stormMaxCrashes, timing.stormWindow),
				"Repair tunnel")
			return
		}

		// Between-retry backoff (capped). Interruptible by Stop().
		s.publish(StageDegraded, s.probeURL,
			fmt.Sprintf("cloudflared exited: %v — retrying in %s", exitErr, backoff),
			"Repair tunnel")

		select {
		case <-ctx.Done():
			s.publish(StageStopped, "", "stopped by caller", "")
			return
		case <-time.After(backoff):
		}

		// Exponential backoff with cap.
		backoff *= 2
		if backoff > timing.maxBackoff {
			backoff = timing.maxBackoff
		}
	}
}

// runOnce starts cloudflared and returns when either the child exits or
// the probe-failure threshold is hit. The returned error is the root
// cause the caller uses to classify the retry decision.
func (s *Supervisor) runOnce(ctx context.Context, timing supervisorTiming) error {
	childCtx, childCancel := context.WithCancel(ctx)
	defer childCancel()

	// --no-autoupdate: Forge manages the binary; we don't want cloudflared
	// silently replacing itself.
	// --config:       point at our managed config, not the user's ~/.cloudflared
	cmd := exec.CommandContext(childCtx, s.bin,
		"tunnel", "run",
		"--no-autoupdate",
		"--config", s.cfg.ConfigPath,
		s.cfg.TunnelUUID,
	)
	hideWindow(cmd)

	// Merge stdout/stderr into a single pipe so the "logs" view in the UI
	// shows things in order; detailed parsing isn't needed for Named
	// tunnels because the hostname is known ahead of time.
	pr, pw := io.Pipe()
	cmd.Stdout = pw
	cmd.Stderr = pw

	if err := cmd.Start(); err != nil {
		pr.Close()
		pw.Close()
		return fmt.Errorf("cloudflared start: %w", err)
	}

	// Drain output so the pipe buffer doesn't fill up and wedge the child.
	// We discard on purpose — named-tunnel URLs are already known; the
	// logs are only interesting when debugging, and the user can run
	// cloudflared by hand for that.
	go func() {
		defer pr.Close()
		scanner := bufio.NewScanner(pr)
		for scanner.Scan() {
			// intentional discard
		}
	}()

	// Give cloudflared a grace period to finish DNS handshake / cert
	// provisioning before the first probe. Without this every cold start
	// would look like a probe failure for the first few seconds.
	select {
	case <-time.After(timing.postStartGrace):
	case <-childCtx.Done():
		_ = cmd.Wait()
		pw.Close()
		return childCtx.Err()
	}

	// Probe loop. We run probes on a ticker, while simultaneously
	// watching for the child to exit. Whichever condition trips first
	// wins.
	probeFailures := 0
	ticker := time.NewTicker(timing.probeInterval)
	defer ticker.Stop()

	waitCh := make(chan error, 1)
	go func() {
		waitCh <- cmd.Wait()
		pw.Close()
	}()

	// Fire an immediate first probe so healthy startups transition out
	// of Starting quickly rather than waiting a full probeInterval.
	s.probeAndReport(ctx, &probeFailures, timing)

	for {
		select {
		case <-childCtx.Done():
			<-waitCh
			return childCtx.Err()

		case exitErr := <-waitCh:
			if exitErr == nil {
				// cloudflared exited cleanly — surprising for `tunnel run`,
				// treat as a crash so the backoff kicks in.
				return errors.New("cloudflared exited unexpectedly with status 0")
			}
			return exitErr

		case <-ticker.C:
			if s.probeAndReport(ctx, &probeFailures, timing) {
				// too many consecutive probe failures — treat as a crash so
				// the outer loop restarts the child. Kill child first or
				// we'd leak a zombie cloudflared.
				childCancel()
				<-waitCh
				return fmt.Errorf("probe failed %d times in a row", timing.probeFailureMax)
			}
		}
	}
}

// probeAndReport runs one health probe and updates the failure counter.
// Returns true when the caller should abort the child (too many failures).
//
// The counter resets on success — a single flaky probe does not escalate.
func (s *Supervisor) probeAndReport(ctx context.Context, failures *int, timing supervisorTiming) bool {
	probeCtx, cancel := context.WithTimeout(ctx, timing.probeTimeoutEach)
	defer cancel()

	if err := ProbeHTTP(probeCtx, s.probeURL); err != nil {
		*failures++
		if *failures >= timing.probeFailureMax {
			s.publish(StageDegraded, s.probeURL,
				fmt.Sprintf("health probe failed %d times: %v", *failures, err),
				"Repair tunnel")
			return true
		}
		// Not yet over the threshold — keep saying Starting/Healthy
		// based on current state, don't flap to Degraded on one blip.
		return false
	}

	*failures = 0
	s.publish(StageHealthy, s.probeURL, "", "")
	return false
}

// publish is the single write-point to the Ranker. Centralised so
// timestamps are consistent and the Mode field can never drift.
func (s *Supervisor) publish(stage HealthStage, url, lastErr, hint string) {
	now := time.Now()
	var lastCheck *time.Time
	if stage == StageHealthy || stage == StageDegraded {
		lastCheck = &now
	}
	s.ranker.Set(HealthState{
		Mode:         ModeIDNamed,
		Stage:        stage,
		URL:          url,
		LastError:    lastErr,
		LastCheckAt:  lastCheck,
		RecoveryHint: hint,
	})
}

// crashTracker implements the "no more than N crashes in W seconds"
// restart-storm guard. Kept private — only Supervisor uses it.
type crashTracker struct {
	window   time.Duration
	limit    int
	recorded []time.Time
}

func newCrashTracker(window time.Duration, limit int) *crashTracker {
	return &crashTracker{window: window, limit: limit}
}

func (c *crashTracker) record(t time.Time) {
	c.recorded = append(c.recorded, t)
	c.evict(t)
}

func (c *crashTracker) stormTripped() bool {
	return len(c.recorded) >= c.limit
}

// evict drops entries older than (now - window). Amortised O(1) because
// the slice never grows beyond `limit` in practice.
func (c *crashTracker) evict(now time.Time) {
	cutoff := now.Add(-c.window)
	for len(c.recorded) > 0 && c.recorded[0].Before(cutoff) {
		c.recorded = c.recorded[1:]
	}
}

// DefaultForgeTunnelDir returns the managed config directory
// (~/.forge/tunnel/). Callers wanting the config path can join this with
// "config.yml"; credentials go in "<uuid>.json". Exposed so handlers and
// the setup wizard stay in sync about where files live.
func DefaultForgeTunnelDir() string {
	return filepath.Join(BinDir(), "..", "tunnel")
}
