// hooks_hookspath_test.go — the ledger gate must live in the hook git actually runs.
//
// The defect these pin: Forge's own scaffold sets core.hooksPath to .forge/hooks
// and writes its "Enhanced" hook there, while the ledger hook was written into
// .git/hooks — a directory git had been told to ignore. Every commit in every
// scaffolded repository ran the scaffold hook alone, and the ledger gate never
// executed anywhere. "Pre-commit checks passed" was the scaffold talking.
package workflow

import (
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

func writeGitConfigForTest(t *testing.T, root, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(root, ".git", "config"), []byte(content), 0o644); err != nil {
		t.Fatalf("writing .git/config: %v", err)
	}
}

// scaffoldHookForTest is the shape of the hook Forge's Workflow Architect writes:
// its own header, its own checks, and a final exit 0 of its own.
const scaffoldHookForTest = "#!/usr/bin/env bash\n" +
	"# Forge Workflow Pre-Commit Hook (Enhanced)\n" +
	"# Generated by Forge Terminal Workflow Architect\n" +
	"\n" +
	"set +e\n" +
	"violations=()\n" +
	"echo \"scaffold checks ran\"\n" +
	"if [[ ${#violations[@]} -gt 0 ]]; then\n" +
	"    exit 1\n" +
	"fi\n" +
	"exit 0\n"

func writeHookForTest(t *testing.T, hookPath, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(hookPath), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(hookPath, []byte(content), 0o755); err != nil {
		t.Fatal(err)
	}
}

func TestEffectiveHooksDirDefaultsToGitHooks(t *testing.T) {
	dir := t.TempDir()
	makeGitDir(t, dir)

	got, err := EffectiveHooksDir(dir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if got != filepath.Join(dir, ".git", "hooks") {
		t.Errorf("with no core.hooksPath the default is .git/hooks, got %q", got)
	}
}

func TestEffectiveHooksDirHonoursCoreHooksPath(t *testing.T) {
	dir := t.TempDir()
	makeGitDir(t, dir)
	writeGitConfigForTest(t, dir, "[core]\n\trepositoryformatversion = 0\n\thooksPath = .forge/hooks\n[remote \"origin\"]\n\turl = x\n")

	got, err := EffectiveHooksDir(dir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if got != filepath.Join(dir, ".forge", "hooks") {
		t.Errorf("core.hooksPath must win, got %q", got)
	}
}

func TestEffectiveHooksDirReadsTheSharedConfigOfAWorktree(t *testing.T) {
	// A linked worktree's .git is a file pointing at <main>/.git/worktrees/<name>,
	// and that directory names the shared config through a commondir file.
	mainRepository := t.TempDir()
	makeGitDir(t, mainRepository)
	writeGitConfigForTest(t, mainRepository, "[core]\n\thooksPath = .forge/hooks\n")
	worktreeState := filepath.Join(mainRepository, ".git", "worktrees", "tab-3")
	if err := os.MkdirAll(worktreeState, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(worktreeState, "commondir"), []byte("../..\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	worktreeRoot := t.TempDir()
	if err := os.WriteFile(filepath.Join(worktreeRoot, ".git"), []byte("gitdir: "+worktreeState+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	got, err := EffectiveHooksDir(worktreeRoot)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	// A relative hooksPath is relative to the worktree the commit is made in.
	if got != filepath.Join(worktreeRoot, ".forge", "hooks") {
		t.Errorf("expected the worktree's own .forge/hooks, got %q", got)
	}
}

func TestEnsureHookInstalled_WritesWhereGitLooks(t *testing.T) {
	dir := t.TempDir()
	makeGitDir(t, dir)
	writeGitConfigForTest(t, dir, "[core]\n\thooksPath = .forge/hooks\n")

	if err := EnsureHookInstalled(dir); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if _, err := os.Stat(filepath.Join(dir, ".forge", "hooks", "pre-commit")); err != nil {
		t.Error("the hook must be written into the directory core.hooksPath names")
	}
	if _, err := os.Stat(filepath.Join(dir, ".git", "hooks", "pre-commit")); err == nil {
		t.Error("nothing should be written into .git/hooks when git has been told to look elsewhere")
	}
}

func TestEnsureHookInstalled_MergesTheLedgerGateIntoTheScaffoldHook(t *testing.T) {
	dir := t.TempDir()
	makeGitDir(t, dir)
	hookPath := filepath.Join(dir, ".git", "hooks", "pre-commit")
	writeHookForTest(t, hookPath, scaffoldHookForTest)

	if err := EnsureHookInstalled(dir); err != nil {
		t.Fatalf("a Forge scaffold hook is ours to extend, got: %v", err)
	}

	content, _ := os.ReadFile(hookPath)
	merged := string(content)
	if !strings.Contains(merged, hookMarker) {
		t.Fatal("the merged hook should carry the ledger marker")
	}
	if !strings.Contains(merged, "echo \"scaffold checks ran\"") {
		t.Error("the scaffold's own checks must survive the merge")
	}
	// The scaffold ends in exit 0, so the ledger step is only reached if it
	// sits before the scaffold's first statement.
	if strings.Index(merged, "workflow preflight") > strings.Index(merged, "set +e") {
		t.Error("the ledger gate must run before the scaffold's own checks, not after its exit")
	}
	if !strings.HasPrefix(merged, "#!/usr/bin/env bash\n") {
		t.Error("the scaffold's shebang must stay on line one")
	}

	// A second call must not stack a second copy.
	if err := EnsureHookInstalled(dir); err != nil {
		t.Fatal(err)
	}
	again, _ := os.ReadFile(hookPath)
	if strings.Count(string(again), "workflow preflight") != strings.Count(merged, "workflow preflight") {
		t.Error("merging twice must not duplicate the ledger gate")
	}
}

func TestEnsureHookInstalled_NamesAForeignHookInsteadOfSilence(t *testing.T) {
	dir := t.TempDir()
	makeGitDir(t, dir)
	hookPath := filepath.Join(dir, ".git", "hooks", "pre-commit")
	foreign := "#!/bin/sh\necho custom\n"
	writeHookForTest(t, hookPath, foreign)

	err := EnsureHookInstalled(dir)
	if !errors.Is(err, ErrForeignPreCommitHook) {
		t.Fatalf("a hook written by another tool must be reported, not silently skipped; got %v", err)
	}
	content, _ := os.ReadFile(hookPath)
	if string(content) != foreign {
		t.Error("a foreign hook must be left exactly as it was")
	}
}

// ── The merged hook, actually executed ───────────────────────────────────────

// runMergedHookWithStub installs the ledger gate into a scaffold hook and runs
// it under sh with FORGE_BIN pointing at a stub whose preflight exits `status`.
// Skips where sh is not available; the file-content tests above still run.
func runMergedHookWithStub(t *testing.T, status int) (output string, exitCode int) {
	t.Helper()
	shell, err := exec.LookPath("sh")
	if err != nil {
		t.Skip("sh not available; the behavioural hook test needs a POSIX shell")
	}

	dir := t.TempDir()
	makeGitDir(t, dir)
	if err := os.WriteFile(filepath.Join(dir, ".git", "HEAD"), []byte("ref: refs/heads/feature/x\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	hookPath := filepath.Join(dir, ".git", "hooks", "pre-commit")
	writeHookForTest(t, hookPath, scaffoldHookForTest)
	if err := EnsureHookInstalled(dir); err != nil {
		t.Fatal(err)
	}

	// The stub answers "workflow naming" with success and "workflow preflight"
	// with the requested status, which is all the hook asks of the binary.
	stub := filepath.Join(dir, "forge-stub")
	stubBody := "#!/bin/sh\n" +
		"if [ \"$2\" = \"preflight\" ]; then echo '{\"ok\": false}'; exit " + strconv.Itoa(status) + "; fi\n" +
		"exit 0\n"
	writeHookForTest(t, stub, stubBody)

	command := exec.Command(shell, hookPath)
	command.Dir = dir
	command.Env = append(os.Environ(), "FORGE_BIN="+filepath.ToSlash(stub))
	combined, runErr := command.CombinedOutput()
	if exitError, isExit := runErr.(*exec.ExitError); isExit {
		exitCode = exitError.ExitCode()
	} else if runErr != nil {
		t.Fatalf("running the hook: %v\n%s", runErr, combined)
	}
	return string(combined), exitCode
}

func TestMergedHookBlocksTheCommitWhenPreflightFails(t *testing.T) {
	output, exitCode := runMergedHookWithStub(t, 2)

	if exitCode != 1 {
		t.Errorf("a failed preflight must block the commit (exit 1), got %d\n%s", exitCode, output)
	}
	if !strings.Contains(output, "BLOCKED") {
		t.Errorf("the developer should be told plainly, got:\n%s", output)
	}
	if strings.Contains(output, "scaffold checks ran") {
		t.Error("a blocked commit should stop before the scaffold's own checks")
	}
}

func TestMergedHookFallsThroughToTheScaffoldWhenPreflightPasses(t *testing.T) {
	output, exitCode := runMergedHookWithStub(t, 0)

	if exitCode != 0 {
		t.Errorf("a passing preflight must not block, got exit %d\n%s", exitCode, output)
	}
	if !strings.Contains(output, "scaffold checks ran") {
		t.Errorf("after the ledger gate passes the scaffold's own checks must still run, got:\n%s", output)
	}
}
