package workflow

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
	"time"
)

// renderTemplate executes a Go template with the given data and returns the output.
func renderTemplate(name, templateText string, data interface{}) (string, error) {
	funcMap := template.FuncMap{
		"upper":    strings.ToUpper,
		"lower":    strings.ToLower,
		"title":    strings.Title,
		"join":     strings.Join,
		"now":      func() string { return time.Now().Format("2006-01-02") },
		"contains": func(slice []ModuleID, target ModuleID) bool { return containsModule(slice, target) },
	}

	tmpl, err := template.New(name).Funcs(funcMap).Parse(templateText)
	if err != nil {
		return "", fmt.Errorf("parsing template %s: %w", name, err)
	}

	var buffer bytes.Buffer
	if err := tmpl.Execute(&buffer, data); err != nil {
		return "", fmt.Errorf("executing template %s: %w", name, err)
	}

	return buffer.String(), nil
}

// RenderCopilotInstructions generates the .github/copilot-instructions.md content.
func RenderCopilotInstructions(config WorkflowConfig) (string, error) {
	return renderTemplate("copilot-instructions", copilotInstructionsTemplate, config)
}

// RenderChangelog generates the initial CHANGELOG.md content.
func RenderChangelog(config WorkflowConfig) (string, error) {
	return renderTemplate("changelog", changelogTemplate, config)
}

// RenderWorkflowJSON generates the .forge/workflow.json content.
func RenderWorkflowJSON(config WorkflowConfig) (string, error) {
	return renderTemplate("workflow-json", workflowJSONTemplate, config)
}

// RenderSkill generates a skill SKILL.md file for the given module.
func RenderSkill(moduleID ModuleID, config WorkflowConfig) (string, error) {
	templateText, exists := skillTemplates[moduleID]
	if !exists {
		return "", fmt.Errorf("no skill template for module: %s", moduleID)
	}
	return renderTemplate(string(moduleID), templateText, config)
}

// RenderPreCommitPS1 generates the PowerShell pre-commit hook script.
func RenderPreCommitPS1(config WorkflowConfig) (string, error) {
	return renderTemplate("pre-commit-ps1", preCommitPS1Template, config)
}

// RenderPreCommitSH generates the Bash pre-commit hook script.
func RenderPreCommitSH(config WorkflowConfig) (string, error) {
	return renderTemplate("pre-commit-sh", preCommitSHTemplate, config)
}

// RenderPRTemplate generates the .github/pull_request_template.md content.
func RenderPRTemplate(config WorkflowConfig) (string, error) {
	return renderTemplate("pr-template", prTemplateContent, config)
}

// ──────────────────────────────────────────────────────────────────────────────
// Template: Copilot Instructions
// ──────────────────────────────────────────────────────────────────────────────

var copilotInstructionsTemplate = `# Copilot Instructions — {{.ProjectName}}

> Auto-generated by Forge Terminal Enterprise Workflow Architect.
> Quality Mode: **{{upper (print .QualityMode)}}** | Project Type: **{{.ProjectType}}**

## Prime Directive

{{if eq .QualityMode "best"}}DO NOT take the fastest or easiest route. Take the BEST route. Your priority is production-readiness, not speed. If a solution is "quick but dirty," it is strictly FORBIDDEN.

Always leverage multiple agents and sub-agents (autopilot_fleet) for parallelizable work. Use Opus-tier models for architecture and complex tasks. Sonnet for features. Haiku only for documentation.{{else}}Balance speed with quality. Use single-agent mode for most tasks. Prioritize working code over perfect code, but maintain minimum quality standards.{{end}}

## Naming Conventions (MANDATORY)

These are not suggestions — they are requirements. Every variable, function, class, and type name MUST be self-documenting.

1. **NEVER use single-letter variable names** — The only exceptions are:
   - ` + "`i`" + `, ` + "`j`" + `, ` + "`k`" + ` for loop iterators
   - ` + "`w`" + ` and ` + "`r`" + ` for HTTP handler (http.ResponseWriter, *http.Request) parameters
   - ` + "`_`" + ` for intentionally unused values
2. **Boolean names** MUST be prefixed with ` + "`is`" + `, ` + "`has`" + `, ` + "`can`" + `, ` + "`should`" + `, or ` + "`was`" + `
   - ✅ ` + "`isActive`" + `, ` + "`hasPermission`" + `, ` + "`canRetry`" + `, ` + "`shouldNotify`" + `
   - ❌ ` + "`active`" + `, ` + "`permission`" + `, ` + "`retry`" + `, ` + "`notify`" + `
3. **Descriptive over clever** — A reader should know a variable's purpose without context:
   - ✅ ` + "`customerLastName`" + `, ` + "`connectionTimeout`" + `, ` + "`retryAttemptCount`" + `
   - ❌ ` + "`x`" + `, ` + "`tmp`" + `, ` + "`val`" + `, ` + "`data`" + `, ` + "`str`" + `
4. **Function names** MUST be verb-first: ` + "`createUser`" + `, ` + "`calculateTotal`" + `, ` + "`validateInput`" + `
5. **Constants** use UPPER_SNAKE_CASE or descriptive camelCase — never abbreviated

## Comment Standards (MANDATORY)

Code comments MUST be readable by someone who is not a developer. Write for a technical project manager, not a compiler.

1. **Every file** MUST have a top-level comment explaining its purpose in one sentence
2. **Every exported/public function** MUST have a doc comment explaining what it does and why
3. **Complex logic blocks** (conditionals, algorithms, state machines) MUST have inline comments explaining the "why," not the "what"
4. **Do NOT comment obvious code** — ` + "`// increment counter`" + ` above ` + "`counter++`" + ` is noise
5. **Write for comprehension** — Comments should answer "Why does this exist?" and "What business problem does this solve?"

## Code Structure

1. **Small functions** — Prefer functions under 40 lines. Extract complex logic into well-named helpers.
2. **Early returns** — Use guard clauses instead of deep nesting
3. **No magic numbers** — Every literal number or string must be a named constant with a comment
4. **Logical grouping** — Group related functions with section comments (` + "`// ── Section ──`" + `)
5. **Import ordering** — Standard library → internal packages → external dependencies

{{if contains .EnabledModules "branching-strategy"}}## Branching Strategy

This project uses **GitHub Flow**:
- All work happens on feature branches: ` + "`feature/*`" + `, ` + "`fix/*`" + `, ` + "`chore/*`" + `, ` + "`docs/*`" + `
- NEVER commit directly to ` + "`main`" + `
- Every merge to ` + "`main`" + ` requires a Pull Request
- Branch names must be descriptive: ` + "`feature/add-user-authentication`" + ` not ` + "`feature/auth`" + `
{{end}}
{{if contains .EnabledModules "documentation"}}## Documentation Discipline

- **CHANGELOG.md** is the single source of truth for "what changed"
- Update CHANGELOG.md in every PR that modifies functionality
- Do NOT create auxiliary summary documents, status files, or task logs
- The README is maintained but never duplicated into other docs
{{end}}
{{if contains .EnabledModules "testing-standards"}}## Testing Requirements

- Write tests BEFORE implementation (TDD: Red → Green → Refactor)
- Separate test layers: Unit (mocked dependencies), Integration (real services), E2E (full stack)
- Unit tests must complete in <10ms each
- Every new source file should have a corresponding test file
{{end}}
{{if contains .EnabledModules "multi-agent"}}## Multi-Agent Orchestration

- For tasks involving 3+ files, use sub-agents (autopilot_fleet) to parallelize
- Architecture tasks → Opus-tier model
- Feature implementation → Sonnet-tier model
- Documentation → Haiku-tier model
- Always classify task complexity before choosing approach
{{end}}
`

// ──────────────────────────────────────────────────────────────────────────────
// Template: CHANGELOG.md
// ──────────────────────────────────────────────────────────────────────────────

var changelogTemplate = `# Changelog — {{.ProjectName}}

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

### Added
- Enterprise workflow initialized with Forge Terminal Workflow Architect

### Changed

### Fixed

### Removed
`

// ──────────────────────────────────────────────────────────────────────────────
// Template: .forge/workflow.json
// ──────────────────────────────────────────────────────────────────────────────

var workflowJSONTemplate = `{
  "version": "1.0.0",
  "projectName": "{{.ProjectName}}",
  "projectType": "{{.ProjectType}}",
  "qualityMode": "{{.QualityMode}}",
  "enabledModules": [{{range $i, $m := .EnabledModules}}{{if $i}}, {{end}}"{{$m}}"{{end}}],
  "tutorSettings": {
    "autoNotify": {{.TutorSettings.AutoNotify}},
    "defaultDepth": "{{.TutorSettings.DefaultDepth}}",
    "auditNaming": {{.TutorSettings.AuditNaming}},
    "auditComments": {{.TutorSettings.AuditComments}}
  },
  "prReviewSettings": {
    "strategy": "{{.PRReviewSettings.Strategy}}",
    "autoTrigger": {{.PRReviewSettings.AutoTrigger}},
    "requireChangelog": {{.PRReviewSettings.RequireChangelog}},
    "agentStrictness": "{{.PRReviewSettings.AgentStrictness}}",
    "agentFocusAreas": [{{range $i, $a := .PRReviewSettings.AgentFocusAreas}}{{if $i}}, {{end}}"{{$a}}"{{end}}]
  },
  "appliedAt": "{{now}}"
}
`

// ──────────────────────────────────────────────────────────────────────────────
// Skill Templates
// ──────────────────────────────────────────────────────────────────────────────

var skillTemplates = map[ModuleID]string{
	ModuleBranchingStrategy: branchingStrategySkill,
	ModuleCodeQuality:       codeQualitySkill,
	ModuleTestingStandards:  testingStandardsSkill,
	ModulePRWorkflow:        prWorkflowSkill,
	ModuleDocumentation:     documentationSkill,
	ModuleMultiAgent:        multiAgentSkill,
	ModuleCodeTutor:         codeTutorWorkflowSkill,
	ModuleWorkflowEnforcer:  workflowEnforcerSkill,
}

var branchingStrategySkill = `---
name: branching-strategy
description: "Enforces GitHub Flow branching strategy. Activates on keywords: branch, merge, commit, push, pull request, PR, git."
---

# Branching Strategy — GitHub Flow

## Rules (MANDATORY)

1. **NEVER commit directly to ` + "`main`" + `** — All work happens on feature branches
2. **Branch naming convention:**
   - ` + "`feature/<descriptive-name>`" + ` — New functionality
   - ` + "`fix/<descriptive-name>`" + ` — Bug fixes
   - ` + "`chore/<descriptive-name>`" + ` — Maintenance, dependency updates
   - ` + "`docs/<descriptive-name>`" + ` — Documentation only
3. **Every merge to main requires a Pull Request** — No exceptions
4. **Branch names MUST be descriptive:** ` + "`feature/add-user-authentication`" + ` not ` + "`feature/auth`" + `
5. **Delete branches after merge** — Keep the branch list clean
6. **Rebase before merge** when the branch is behind main (keep history linear)

## Workflow

` + "```" + `
1. Create branch:  git checkout -b feature/descriptive-name
2. Make changes:   Commit often with clear messages
3. Push:           git push origin feature/descriptive-name
4. Open PR:        Create PR with filled template and checklist
5. Review:         Address feedback, ensure CI passes
6. Merge:          Squash merge for features, merge commit for releases
7. Clean up:       Delete the feature branch
` + "```" + `

## Commit Message Format

` + "```" + `
<type>: <description>

[optional body explaining WHY, not WHAT]

Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>
` + "```" + `

Types: feat, fix, chore, docs, test, refactor, perf
`

var codeQualitySkill = `---
name: code-quality
description: "Enforces human-readable code standards. Activates on ANY implementation, refactor, feature, bugfix, or code modification task."
---

# Code Quality Standards

## Naming Rules (ZERO TOLERANCE)

These rules are not suggestions. They are hard requirements enforced by pre-commit hooks.

### Variable Names
- ❌ FORBIDDEN: ` + "`x`" + `, ` + "`y`" + `, ` + "`z`" + `, ` + "`tmp`" + `, ` + "`val`" + `, ` + "`data`" + `, ` + "`str`" + `, ` + "`buf`" + `, ` + "`res`" + `, ` + "`req`" + ` (except HTTP handler params), ` + "`ctx`" + ` (except Go context.Context)
- ✅ REQUIRED: Self-documenting names that a non-developer can understand
- Examples:
  - ` + "`x`" + ` → ` + "`horizontalPosition`" + ` or ` + "`customerAge`" + ` (depends on context)
  - ` + "`tmp`" + ` → ` + "`temporaryFilePath`" + ` or ` + "`swapValue`" + `
  - ` + "`buf`" + ` → ` + "`responseBuffer`" + ` or ` + "`logMessageBuilder`" + `

### Boolean Names
MUST be prefixed: ` + "`is`" + `, ` + "`has`" + `, ` + "`can`" + `, ` + "`should`" + `, ` + "`was`" + `

### Function Names
MUST be verb-first: ` + "`createUser`" + `, ` + "`validateEmail`" + `, ` + "`calculateTotalRevenue`" + `

### Constants
MUST be descriptive: ` + "`MaxRetryAttempts`" + ` not ` + "`MAX`" + `, ` + "`DefaultTimeoutSeconds`" + ` not ` + "`TIMEOUT`" + `

## Comment Standards

Comments MUST be readable by a non-developer (technical project manager level).

1. Every file: top-level purpose comment
2. Every public function: doc comment explaining WHAT and WHY
3. Complex logic: inline comments explaining the business reasoning
4. NO commenting obvious code (` + "`// increment counter`" + ` is noise)

## Structure Rules

1. Functions under 40 lines preferred; extract helpers for complex logic
2. Early returns / guard clauses over deep nesting
3. No magic numbers — use named constants
4. Group related functions with section comments
5. Imports: stdlib → internal → external
`

var testingStandardsSkill = `---
name: testing-standards
description: "Enforces TDD workflow and test quality standards. Activates on keywords: test, spec, validate, coverage, TDD, unit test, integration test."
---

# Testing Standards

## TDD Workflow (MANDATORY)

1. **RED:** Write a failing test that describes the expected behavior
2. **GREEN:** Write the minimum code to make the test pass
3. **REFACTOR:** Improve the code while keeping tests green

## Test Layer Separation

| Layer | Scope | Dependencies | Speed |
|-------|-------|-------------|-------|
| Unit | Individual functions, components | ALL mocked | <10ms per test |
| Integration | API handlers, data persistence | Real services (testcontainers) | <5s per test |
| E2E | Full user journeys | Real stack | <30s per test |

## Rules

1. **Every new source file MUST have a corresponding test file**
2. **Never mock what you don't own** — wrap external APIs in interfaces first
3. **Test behavior, not implementation** — tests should survive refactoring
4. **Descriptive test names:** ` + "`TestCreateUser_WithDuplicateEmail_ReturnsConflictError`" + `
5. **Arrange / Act / Assert** structure in every test
`

var prWorkflowSkill = `---
name: pr-workflow
description: "Enforces pull request standards. Activates on keywords: PR, pull request, merge, review, code review."
---

# Pull Request Workflow

## PR Requirements

1. **Title:** Clear, descriptive — matches commit message format (` + "`type: description`" + `)
2. **Description:** Explain WHY, not just WHAT. Link to related issues.
3. **Checklist:** Complete the PR template checklist (all items checked)
4. **CHANGELOG:** MUST be updated if the PR changes functionality
5. **Tests:** All new/changed code must have tests. CI must pass.
6. **Review:** At least one approval required before merge.

## Merge Strategy

- **Feature branches:** Squash merge (clean single commit on main)
- **Release branches:** Merge commit (preserve release history)
- **Hotfix branches:** Squash merge

## After Merge

1. Delete the feature branch
2. Verify CI passes on main
3. If applicable, tag a release
`

var documentationSkill = `---
name: documentation
description: "Enforces documentation discipline. Activates on keywords: document, readme, changelog, docs, documentation."
---

# Documentation Discipline

## The One Rule

**CHANGELOG.md is the single source of truth for what changed.**

## What This Means

1. **DO** update CHANGELOG.md in every PR that changes functionality
2. **DO** maintain README.md with setup instructions and architecture overview
3. **DO NOT** create auxiliary summary documents per task
4. **DO NOT** create markdown files to describe what an AI agent just did
5. **DO NOT** create status files, progress logs, or task tracking documents in the repo

## CHANGELOG Format

` + "```markdown" + `
## [Unreleased]

### Added
- One-line summary of new feature (#PR-number)

### Changed
- One-line summary of behavior change (#PR-number)

### Fixed
- One-line summary of bug fix (#PR-number)

### Removed
- One-line summary of removed feature (#PR-number)

## [v1.2.0] - 2026-04-04

### Added
- ...
` + "```" + `

## Architecture Decisions

Document architecture decisions in **code comments**, not separate files.
Use this format in the relevant source file:

` + "```" + `
// ARCHITECTURE DECISION: [Brief title]
// What: [What was decided]
// Why: [Reasoning]
// Alternative: [What else was considered]
` + "```" + `
`

var multiAgentSkill = `---
name: multi-agent
description: "Enforces multi-agent orchestration for quality. Activates on keywords: implement, build, create, refactor, architecture, design, complex."
---

# Multi-Agent Orchestration

## Quality Mode: {{if eq .QualityMode "best"}}BEST{{else}}FAST{{end}}

{{if eq .QualityMode "best"}}### BEST Mode Rules

1. **ALWAYS use sub-agents** (autopilot_fleet) for tasks involving 3+ independent files
2. **Task Classification → Model Routing:**
   - Architecture/Design (complexity 8-10) → Opus-tier model
   - Feature implementation (complexity 5-7) → Sonnet-tier model
   - Bugfix (complexity 4-6) → Sonnet-tier model
   - Documentation (complexity 1-3) → Haiku-tier model
3. **Parallel exploration** — Use explore agents to investigate multiple code areas simultaneously
4. **Never sacrifice quality for speed** — If a task needs 5 turns to get right, take 5 turns
5. **Code review before delivery** — Always review your own output against the project's code quality standards{{else}}### FAST Mode Rules

1. Use single-agent mode for most tasks
2. Use sub-agents only for tasks involving 5+ files
3. Prefer Sonnet-tier for all tasks
4. Minimize conversation turns
{{end}}
`

var codeTutorWorkflowSkill = `---
name: code-tutor-workflow
description: "Integrates Code Tutor with enterprise workflow. Activates on keywords: tutor, teach, explain, walkthrough, learn, understand."
---

# Code Tutor Integration

## Behavior

When Code Tutor is active in the workflow:

1. **File change notifications** — When files are created or modified, the system sends a notification: "N files changed — want a walkthrough?"
2. **Explanation depth levels:**
   - **Overview** — General, mildly technical summary suitable for project managers
   - **Technical** — Standard developer-level explanation of logic and patterns
   - **Line-by-Line** — Detailed walk-through of every significant line
3. **Quality auditing** — Tutor explanations flag naming violations, missing comments, and readability concerns

## Agent Integration

When creating or modifying files with Code Tutor active:

1. Write code that is optimized for learning — clear structure, logical flow
2. Add brief inline comments on non-obvious logic (the "why" moments)
3. Use architecture decision blocks for significant structural decisions
4. Ensure every public/exported symbol has a documentation comment
`

var workflowEnforcerSkill = `---
name: workflow-enforcer
description: "MANDATORY for all code changes. Enforces enterprise workflow standards. Activates on ANY implementation, refactor, bugfix, feature, build, create, modify, update, fix, add, change, or code modification task."
---

# Workflow Enforcer — Enterprise Standards

> ⚠️ This skill is MANDATORY. It applies to EVERY coding task in this project.
> Read .forge/workflow.json for this project's active configuration.

## SELF-CHECK PROTOCOL

Before delivering ANY code change, verify your output against these rules:

### ✅ Naming Check
- [ ] No single-letter variables (except i/j/k in loops, w/r in HTTP handlers)
- [ ] All booleans prefixed with is/has/can/should/was
- [ ] All functions are verb-first
- [ ] A non-developer can understand every name without context

### ✅ Comment Check
- [ ] Every new file has a top-level purpose comment
- [ ] Every public/exported function has a doc comment
- [ ] Complex logic blocks have "why" comments (not "what" comments)
- [ ] Comments are readable by a technical project manager

### ✅ Structure Check
- [ ] No function exceeds 40 lines (extract helpers if needed)
- [ ] Guard clauses used instead of deep nesting
- [ ] No magic numbers or strings (use named constants)
- [ ] Imports are logically grouped

### ✅ Workflow Check
- [ ] Working on a feature branch (not main)
- [ ] CHANGELOG.md updated if functionality changed
- [ ] Tests written for new/changed code
- [ ] Commit message follows format: type: description

### ✅ Quality Mode Check
{{if eq .QualityMode "best"}}- [ ] Sub-agents used for parallelizable work (3+ independent files)
- [ ] Task classified and appropriate model tier selected
- [ ] Code reviewed against quality standards before delivery{{else}}- [ ] Code meets minimum quality bar{{end}}

## ENFORCEMENT

If you find yourself about to deliver code that violates any of these rules:
1. STOP
2. Fix the violation
3. Re-verify the entire checklist
4. Only then deliver

These are not suggestions. They are requirements.
`

// ──────────────────────────────────────────────────────────────────────────────
// Template: Pre-Commit Hook (PowerShell)
// ──────────────────────────────────────────────────────────────────────────────

// preCommitPS1Template is built with string concatenation to avoid
// Go raw-string / PowerShell backtick conflicts.
var preCommitPS1Template = "#!/usr/bin/env pwsh\n" +
	"# Enterprise Workflow Pre-Commit Hook\n" +
	"# Generated by Forge Terminal Workflow Architect\n" +
	"# Validates naming conventions, CHANGELOG updates, and branch naming.\n" +
	"# Bypass with: git commit --no-verify (bypasses are logged)\n" +
	"\n" +
	"$ErrorActionPreference = \"Continue\"\n" +
	"$violations = @()\n" +
	"$warnings = @()\n" +
	"\n" +
	"# Branch Naming Check\n" +
	"$currentBranch = git branch --show-current 2>$null\n" +
	"$validBranchPattern = \"^(main|master|develop|feature/.+|fix/.+|chore/.+|docs/.+|hotfix/.+|release/.+)$\"\n" +
	"if ($currentBranch -and $currentBranch -notmatch $validBranchPattern) {\n" +
	"    $violations += \"BRANCH: '$currentBranch' does not match naming convention\"\n" +
	"}\n" +
	"\n" +
	"# Get Staged Files\n" +
	"$stagedFiles = git diff --cached --name-only --diff-filter=ACM 2>$null\n" +
	"if (-not $stagedFiles) { exit 0 }\n" +
	"\n" +
	"$sourceExtensions = @(\".go\", \".js\", \".jsx\", \".ts\", \".tsx\", \".py\", \".rs\", \".java\", \".cs\")\n" +
	"$sourceFiles = $stagedFiles | Where-Object {\n" +
	"    $extension = [System.IO.Path]::GetExtension($_)\n" +
	"    $sourceExtensions -contains $extension\n" +
	"}\n" +
	"\n" +
	"# Naming Convention Check\n" +
	"$allowedSingleLetters = @('i', 'j', 'k', 'w', 'r', '_')\n" +
	"foreach ($filePath in $sourceFiles) {\n" +
	"    if (-not (Test-Path $filePath)) { continue }\n" +
	"    $lineNumber = 0\n" +
	"    foreach ($line in (Get-Content $filePath -ErrorAction SilentlyContinue)) {\n" +
	"        $lineNumber++\n" +
	"        if ($line -match '^\\s*(var|let|const|)\\s*([a-z])\\s*[:=]') {\n" +
	"            $varName = $Matches[2]\n" +
	"            if ($varName -and $varName.Length -eq 1 -and $allowedSingleLetters -notcontains $varName) {\n" +
	"                $warnings += \"NAMING: ${filePath}:${lineNumber} - Single-letter variable '$varName'\"\n" +
	"            }\n" +
	"        }\n" +
	"    }\n" +
	"}\n" +
	"\n" +
	"# CHANGELOG Check\n" +
	"$hasSourceChanges = ($sourceFiles | Measure-Object).Count -gt 0\n" +
	"$changelogUpdated = $stagedFiles | Where-Object { $_ -match \"CHANGELOG\\.md$\" }\n" +
	"if ($hasSourceChanges -and -not $changelogUpdated) {\n" +
	"    $warnings += \"CHANGELOG: Source files changed but CHANGELOG.md was not updated\"\n" +
	"}\n" +
	"\n" +
	"# Report Results\n" +
	"if ($violations.Count -gt 0) {\n" +
	"    Write-Host \"\"\n" +
	"    Write-Host \"PRE-COMMIT VIOLATIONS (blocking):\" -ForegroundColor Red\n" +
	"    foreach ($v in $violations) { Write-Host \"  * $v\" -ForegroundColor Red }\n" +
	"}\n" +
	"if ($warnings.Count -gt 0) {\n" +
	"    Write-Host \"\"\n" +
	"    Write-Host \"PRE-COMMIT WARNINGS (non-blocking):\" -ForegroundColor Yellow\n" +
	"    foreach ($w in $warnings) { Write-Host \"  * $w\" -ForegroundColor Yellow }\n" +
	"}\n" +
	"if ($violations.Count -eq 0 -and $warnings.Count -eq 0) {\n" +
	"    Write-Host \"Pre-commit checks passed\" -ForegroundColor Green\n" +
	"}\n" +
	"\n" +
	"if ($violations.Count -gt 0) {\n" +
	"    Write-Host \"Commit blocked. Fix violations or use --no-verify to bypass.\" -ForegroundColor Red\n" +
	"    exit 1\n" +
	"}\n" +
	"exit 0\n"

// ──────────────────────────────────────────────────────────────────────────────
// Template: Pre-Commit Hook (Bash)
// ──────────────────────────────────────────────────────────────────────────────

// preCommitSHTemplate is built with string concatenation to avoid
// Go raw-string delimiter conflicts with shell syntax.
var preCommitSHTemplate = "#!/usr/bin/env bash\n" +
	"# Enterprise Workflow Pre-Commit Hook\n" +
	"# Generated by Forge Terminal Workflow Architect\n" +
	"# Bypass with: git commit --no-verify (bypasses are logged)\n" +
	"\n" +
	"set +e\n" +
	"violations=()\n" +
	"warnings=()\n" +
	"\n" +
	"# Branch Naming Check\n" +
	"current_branch=$(git branch --show-current 2>/dev/null)\n" +
	"if [[ -n \"$current_branch\" ]] && ! echo \"$current_branch\" | grep -qE \"^(main|master|develop|feature/.+|fix/.+|chore/.+|docs/.+|hotfix/.+|release/.+)$\"; then\n" +
	"    violations+=(\"BRANCH: '$current_branch' does not match naming convention\")\n" +
	"fi\n" +
	"\n" +
	"# Get Staged Files\n" +
	"staged_files=$(git diff --cached --name-only --diff-filter=ACM 2>/dev/null)\n" +
	"[[ -z \"$staged_files\" ]] && exit 0\n" +
	"\n" +
	"# Filter to source files\n" +
	"source_files=$(echo \"$staged_files\" | grep -E '\\.(go|js|jsx|ts|tsx|py|rs|java|cs)$')\n" +
	"\n" +
	"# CHANGELOG Check\n" +
	"has_source_changes=false\n" +
	"[[ -n \"$source_files\" ]] && has_source_changes=true\n" +
	"changelog_updated=$(echo \"$staged_files\" | grep -c \"CHANGELOG\\.md$\")\n" +
	"if $has_source_changes && [[ \"$changelog_updated\" -eq 0 ]]; then\n" +
	"    warnings+=(\"CHANGELOG: Source files changed but CHANGELOG.md was not updated\")\n" +
	"fi\n" +
	"\n" +
	"# Report Results\n" +
	"if [[ ${#violations[@]} -gt 0 ]]; then\n" +
	"    echo -e \"\\n\\033[31mPRE-COMMIT VIOLATIONS (blocking):\\033[0m\"\n" +
	"    for v in \"${violations[@]}\"; do echo -e \"  \\033[31m* $v\\033[0m\"; done\n" +
	"fi\n" +
	"if [[ ${#warnings[@]} -gt 0 ]]; then\n" +
	"    echo -e \"\\n\\033[33mPRE-COMMIT WARNINGS (non-blocking):\\033[0m\"\n" +
	"    for w in \"${warnings[@]}\"; do echo -e \"  \\033[33m* $w\\033[0m\"; done\n" +
	"fi\n" +
	"if [[ ${#violations[@]} -eq 0 ]] && [[ ${#warnings[@]} -eq 0 ]]; then\n" +
	"    echo -e \"\\033[32mPre-commit checks passed\\033[0m\"\n" +
	"fi\n" +
	"\n" +
	"if [[ ${#violations[@]} -gt 0 ]]; then\n" +
	"    echo -e \"\\033[31mCommit blocked. Fix violations or use --no-verify to bypass.\\033[0m\"\n" +
	"    exit 1\n" +
	"fi\n" +
	"exit 0\n"

// ──────────────────────────────────────────────────────────────────────────────
// Template: PR Template
// ──────────────────────────────────────────────────────────────────────────────

var prTemplateContent = `## Description

<!-- Explain WHY this change is needed, not just WHAT it does. Link related issues. -->

## Changes

<!-- Brief bullet points of what changed -->

-

## PR Checklist

- [ ] CHANGELOG.md updated with summary of changes
- [ ] All variable and function names are self-documenting (no single-letter names)
- [ ] Code comments are readable by non-developers
- [ ] Tests written or updated for changed code
- [ ] Branch follows naming convention (feature/*, fix/*, chore/*, docs/*)
{{if contains .EnabledModules "code-tutor"}}- [ ] Code Tutor walkthrough completed for new/changed files
{{end}}
## Testing

<!-- How was this tested? Include test output or screenshots. -->

## Quality Mode: {{upper (print .QualityMode)}}

{{if eq .QualityMode "best"}}<!-- Confirm multi-agent approach was used where applicable -->
- [ ] Sub-agents leveraged for parallelizable work
- [ ] Appropriate model tier used for task complexity
{{end}}
`
