#!/usr/bin/env node
/**
 * mcp-forge-vault — Stdio-to-HTTP proxy that bridges Claude Code to the
 * Forge Terminal built-in MCP server (/api/mcp).
 *
 * Why a proxy? Claude Code requires stdio transport, but Forge Terminal
 * speaks Streamable HTTP (MCP over HTTP/JSON-RPC 2.0). This adapter:
 *   1. Reads the bearer token from ~/.forge/mcp-token (auto-generated by Forge)
 *   2. Probes localhost ports to find the running Forge instance
 *   3. Forwards every MCP request to /api/mcp and returns the response via stdio
 *
 * All tools are discovered dynamically from the live server — no hardcoding.
 */

import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';
import { readFile } from 'fs/promises';
import { homedir } from 'os';
import { join } from 'path';

const PREFERRED_PORTS = [3005, 8333, 8080, 9000, 3000, 3333];

// ── Token ─────────────────────────────────────────────────────────────────────

async function readMCPToken() {
  const tokenPath = join(homedir(), '.forge', 'mcp-token');
  try {
    const raw = await readFile(tokenPath, 'utf8');
    return raw.trim();
  } catch {
    throw new Error(
      `Cannot read MCP token from ${tokenPath}.\n` +
      `Make sure Forge Terminal has been launched at least once to generate the token.`
    );
  }
}

// ── Port detection ─────────────────────────────────────────────────────────────

async function detectForgePort(token) {
  for (const port of PREFERRED_PORTS) {
    try {
      const res = await fetch(`http://localhost:${port}/api/mcp`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`,
        },
        body: JSON.stringify({ jsonrpc: '2.0', id: 0, method: 'initialize', params: { protocolVersion: '2024-11-05', capabilities: {}, clientInfo: { name: 'probe', version: '0' } } }),
        signal: AbortSignal.timeout(1500),
      });
      if (res.status === 200 || res.status === 401) {
        // 200 = valid token, 401 = Forge is up but token mismatch
        if (res.status === 401) {
          throw new Error(`Forge found on port ${port} but token was rejected. Delete ~/.forge/mcp-token and restart Forge to regenerate.`);
        }
        return port;
      }
    } catch (err) {
      if (err.message?.includes('token was rejected')) throw err;
      // connection refused or timeout — try next port
    }
  }
  throw new Error(
    `Forge Terminal does not appear to be running.\n` +
    `Start Forge Terminal, then try again.\n` +
    `Checked ports: ${PREFERRED_PORTS.join(', ')}`
  );
}

// ── Proxy setup ───────────────────────────────────────────────────────────────

async function main() {
  const token = await readMCPToken();
  const port = await detectForgePort(token);

  const baseUrl = new URL(`http://localhost:${port}/api/mcp`);

  // Upstream HTTP client connecting to Forge's built-in MCP server
  const upstream = new Client(
    { name: 'forge-mcp-proxy', version: '1.0.0' },
    { capabilities: {} }
  );

  const httpTransport = new StreamableHTTPClientTransport(baseUrl, {
    requestInit: {
      headers: { Authorization: `Bearer ${token}` },
    },
  });

  await upstream.connect(httpTransport);

  // Discover all tools exposed by the built-in server
  const { tools } = await upstream.listTools();

  // Stdio server re-exposing those tools to Claude Code
  const server = new Server(
    { name: 'forge-terminal', version: '1.0.0' },
    { capabilities: { tools: {} } }
  );

  server.setRequestHandler(ListToolsRequestSchema, async () => ({ tools }));

  server.setRequestHandler(CallToolRequestSchema, async (request) => {
    const result = await upstream.callTool({
      name: request.params.name,
      arguments: request.params.arguments ?? {},
    });
    return result;
  });

  const stdioTransport = new StdioServerTransport();
  await server.connect(stdioTransport);
}

main().catch((err) => {
  process.stderr.write(`[forge-mcp] Fatal: ${err.message}\n`);
  process.exit(1);
});
