#!/usr/bin/env bash
# install-workflow-hooks.sh — install the runtime workflow pre-commit hook.
#
# Mirror of scripts/install-workflow-hooks.ps1 for macOS / Linux users.
set -e

repo="${1:-$(pwd)}"
git_dir="$repo/.git"
if [ ! -d "$git_dir" ]; then
  echo "Not a git repository: $repo" >&2
  exit 1
fi

hooks_dir="$git_dir/hooks"
mkdir -p "$hooks_dir"
hook_path="$hooks_dir/pre-commit"

cat > "$hook_path" <<'HOOK'
#!/usr/bin/env sh
# Forge Terminal — runtime workflow pre-commit gate.
# Generated by scripts/install-workflow-hooks.sh; safe to regenerate.

set -e

if [ "${FORGE_BYPASS:-0}" = "1" ]; then
  ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  reason="${FORGE_BYPASS_REASON:-no reason provided}"
  mkdir -p .forge
  printf "%s bypass: %s\n" "$ts" "$reason" >> .forge/bypasses.log
  echo "[forge] FORGE_BYPASS=1 — workflow gate skipped, logged to .forge/bypasses.log"
  exit 0
fi

branch=$(git symbolic-ref --short HEAD 2>/dev/null || echo "")
case "$branch" in
  main|master)
    echo "[forge] BLOCKED: refusing to commit directly to '$branch'." >&2
    echo "[forge] Create a feature branch first." >&2
    echo "[forge] Set FORGE_BYPASS=1 with FORGE_BYPASS_REASON=... to override." >&2
    exit 1
    ;;
esac

forge_bin=""
if   [ -x "./forge" ];      then forge_bin="./forge"
elif [ -x "./fterm.exe" ];  then forge_bin="./fterm.exe"
elif [ -x "./forge.exe" ];  then forge_bin="./forge.exe"
elif command -v forge >/dev/null 2>&1; then forge_bin="forge"
elif command -v fterm >/dev/null 2>&1; then forge_bin="fterm"
fi

if [ -z "$forge_bin" ]; then
  echo "[forge] WARNING: forge binary not found — skipping ticket preflight." >&2
  exit 0
fi

"$forge_bin" workflow preflight
status=$?
if [ "$status" -eq 0 ]; then
  echo "[forge] workflow gate: PASS"
  exit 0
fi
if [ "$status" -eq 2 ]; then
  echo "[forge] BLOCKED: workflow ticket is missing required gates." >&2
  echo "[forge] Record gates via workflow_gate_record then retry." >&2
  exit 1
fi
echo "[forge] preflight returned unexpected status $status — blocking commit." >&2
exit 1
HOOK

chmod +x "$hook_path"
echo "Installed $hook_path"
