# install-workflow-hooks.ps1 — install the runtime workflow pre-commit hook.
#
# The hook calls `forge workflow preflight` (the same CLI the MCP tool uses)
# and refuses any commit whose .forge/workflow-ticket.json is missing or
# missing one of the required gates: branch-created, tests-written,
# tests-passed.  Set FORGE_BYPASS=1 to override (logged to .forge/bypasses.log).
#
# Usage:
#   .\scripts\install-workflow-hooks.ps1            # install into current repo
#   .\scripts\install-workflow-hooks.ps1 -Path C:\path\to\repo

param(
  [string]$Path = (Get-Location).Path
)

$ErrorActionPreference = 'Stop'

$gitDir = Join-Path $Path ".git"
if (-not (Test-Path $gitDir)) {
  Write-Error "Not a git repository: $Path"
}

$hooksDir = Join-Path $gitDir "hooks"
if (-not (Test-Path $hooksDir)) {
  New-Item -ItemType Directory -Path $hooksDir | Out-Null
}

$hookPath = Join-Path $hooksDir "pre-commit"

# Hook script — POSIX shell so it runs on Windows (Git Bash), macOS, and Linux.
$hookBody = @'
#!/usr/bin/env sh
# Forge Terminal — runtime workflow pre-commit gate.
# Generated by scripts/install-workflow-hooks.ps1; safe to regenerate.

set -e

if [ "${FORGE_BYPASS:-0}" = "1" ]; then
  ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  reason="${FORGE_BYPASS_REASON:-no reason provided}"
  mkdir -p .forge
  printf "%s bypass: %s\n" "$ts" "$reason" >> .forge/bypasses.log
  echo "[forge] FORGE_BYPASS=1 — workflow gate skipped, logged to .forge/bypasses.log"
  exit 0
fi

# Refuse commits straight to main / master.
branch=$(git symbolic-ref --short HEAD 2>/dev/null || echo "")
case "$branch" in
  main|master)
    echo "[forge] BLOCKED: refusing to commit directly to '$branch'." >&2
    echo "[forge] Create a feature branch first (e.g. 'git checkout -b feature/foo')." >&2
    echo "[forge] Set FORGE_BYPASS=1 with FORGE_BYPASS_REASON=... to override." >&2
    exit 1
    ;;
esac

# Locate a forge binary.  Prefer the project-local build, then PATH.
forge_bin=""
if [ -x "./forge" ]; then forge_bin="./forge"
elif [ -x "./fterm.exe" ]; then forge_bin="./fterm.exe"
elif [ -x "./forge.exe" ]; then forge_bin="./forge.exe"
elif command -v forge >/dev/null 2>&1; then forge_bin="forge"
elif command -v fterm >/dev/null 2>&1; then forge_bin="fterm"
fi

if [ -z "$forge_bin" ]; then
  echo "[forge] WARNING: forge binary not found — skipping ticket preflight." >&2
  echo "[forge] Install Forge Terminal or run from a built source tree to enable enforcement." >&2
  exit 0
fi

# Run preflight.  Exit code 2 = required gates missing.
"$forge_bin" workflow preflight
status=$?
if [ "$status" -eq 0 ]; then
  echo "[forge] workflow gate: PASS"
  exit 0
fi
if [ "$status" -eq 2 ]; then
  echo "" >&2
  echo "[forge] BLOCKED: workflow ticket is missing required gates." >&2
  echo "[forge] Record gates via the workflow_gate_record MCP tool, then retry." >&2
  echo "[forge] Required gates: branch-created, tests-written, tests-passed." >&2
  echo "[forge] Override with FORGE_BYPASS=1 FORGE_BYPASS_REASON=... git commit ..." >&2
  exit 1
fi
echo "[forge] preflight returned unexpected status $status — blocking commit." >&2
exit 1
'@

# Normalize to LF line endings so Git Bash on Windows runs the hook cleanly.
$hookBody = $hookBody -replace "`r`n", "`n"
[IO.File]::WriteAllText($hookPath, $hookBody)
Write-Host "Installed $hookPath"
Write-Host "The next 'git commit' will run 'forge workflow preflight' before allowing the commit."
