#Requires -Version 7.0
# sync-skills.ps1 — FORGE-TERMINAL-LOCAL skill bridge.
#
# Embeds forge-terminal's OWN language-tuned skills (.claude/commands/*.md) into forge-terminal's own
#   1. .github/copilot-instructions.md  (between <!-- FORGE-SKILLS-START/END --> markers)
#   2. .aider/forge-system-prompt.md    (full concatenation for --system-prompt injection)
#
# Scope is forge-terminal itself ONLY. It deliberately does NOT push to the global
# ~/.claude/commands directory: skills are distributed PER-REPO (each repo's .github/skills/ is the
# single source for all its tools — see deploy-skills.ps1), so forge-terminal's Go/React-tuned skills
# never leak into other projects' Claude sessions.
#
# Idempotent: safe to run multiple times. Only replaces the marked skill section;
# everything else in copilot-instructions.md is preserved.
#
# Usage:
#   .\scripts\sync-skills.ps1
#   .\scripts\sync-skills.ps1 -DryRun       # Preview changes without writing

[CmdletBinding()]
param(
    [switch]$DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Constants ────────────────────────────────────────────────────────────────

$repoRoot            = Split-Path -Parent $PSScriptRoot
$skillSourceDir      = Join-Path $repoRoot '.claude\commands'
$copilotInstructions = Join-Path $repoRoot '.github\copilot-instructions.md'
$aiderDir            = Join-Path $repoRoot '.aider'
$aiderSystemPrompt   = Join-Path $aiderDir 'forge-system-prompt.md'

$markerStart = '<!-- FORGE-SKILLS-START -->'
$markerEnd   = '<!-- FORGE-SKILLS-END -->'

# Canonical skill order — determines embedding sequence in both outputs
$skillOrder = @(
    'workflow-enforcer',
    'code-quality',
    'framework-first',
    'branching-strategy',
    'code-tutor-workflow',
    'add-command-card'
)

# ── Helpers ──────────────────────────────────────────────────────────────────

function Write-Status {
    param([string]$Symbol, [string]$Message, [string]$Color = 'Cyan')
    Write-Host "  $Symbol " -ForegroundColor $Color -NoNewline
    Write-Host $Message
}

function Write-SectionHeader {
    param([string]$Title)
    Write-Host ''
    Write-Host "── $Title " -ForegroundColor DarkCyan
}

# ── Step 1: Collect skill files ───────────────────────────────────────────────

Write-SectionHeader 'Collecting skills'

if (-not (Test-Path $skillSourceDir)) {
    Write-Error "Skill source directory not found: $skillSourceDir"
    exit 1
}

# Build an ordered list of (name, path, content) objects
$skills = [System.Collections.Generic.List[hashtable]]::new()

foreach ($skillName in $skillOrder) {
    $skillPath = Join-Path $skillSourceDir "$skillName.md"
    if (-not (Test-Path $skillPath)) {
        Write-Status '!' "MISSING: $skillName.md — skipping" 'Yellow'
        continue
    }
    $skillContent = Get-Content $skillPath -Raw -Encoding UTF8
    $skills.Add(@{
        Name    = $skillName
        Path    = $skillPath
        Content = $skillContent.TrimEnd()
    })
    Write-Status '+' "Loaded: $skillName.md ($($skillContent.Length) chars)"
}

# Also pick up any unlisted skills in directory order (future-proof)
$allSkillFiles = Get-ChildItem $skillSourceDir -Filter '*.md' | Sort-Object Name
foreach ($file in $allSkillFiles) {
    $baseName = $file.BaseName
    $alreadyLoaded = $skills | Where-Object { $_.Name -eq $baseName }
    if (-not $alreadyLoaded) {
        $skillContent = Get-Content $file.FullName -Raw -Encoding UTF8
        $skills.Add(@{
            Name    = $baseName
            Path    = $file.FullName
            Content = $skillContent.TrimEnd()
        })
        Write-Status '+' "Loaded (unordered): $($file.Name) ($($skillContent.Length) chars)"
    }
}

if ($skills.Count -eq 0) {
    Write-Error 'No skill files found. Aborting.'
    exit 1
}

# ── Step 2: Build the embedded skill block ────────────────────────────────────

Write-SectionHeader 'Building skill block'

$skillBlockLines = [System.Collections.Generic.List[string]]::new()
$skillBlockLines.Add($markerStart)
$skillBlockLines.Add('')
$skillBlockLines.Add('# Forge Workflow Skills — Canonical Content')
$skillBlockLines.Add('>')
$skillBlockLines.Add('> This section is AUTO-GENERATED by scripts/sync-skills.ps1.')
$skillBlockLines.Add('> Do NOT edit manually. Re-run the script after changing any .claude/commands/*.md file.')
$skillBlockLines.Add('>')
$skillBlockLines.Add("> Last synced: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') | Skills: $($skills.Count)")
$skillBlockLines.Add('')

foreach ($skill in $skills) {
    $skillBlockLines.Add('---')
    $skillBlockLines.Add('')
    $skillBlockLines.Add("## SKILL: $($skill.Name)")
    $skillBlockLines.Add('')
    $skillBlockLines.Add($skill.Content)
    $skillBlockLines.Add('')
    Write-Status '>' "Embedded: $($skill.Name)"
}

$skillBlockLines.Add('---')
$skillBlockLines.Add('')
$skillBlockLines.Add($markerEnd)

$newSkillBlock = $skillBlockLines -join "`n"

# ── Step 3: Update copilot-instructions.md ────────────────────────────────────

Write-SectionHeader 'Updating .github/copilot-instructions.md'

if (-not (Test-Path $copilotInstructions)) {
    Write-Error "copilot-instructions.md not found at: $copilotInstructions"
    exit 1
}

$existingContent = Get-Content $copilotInstructions -Raw -Encoding UTF8

# Detect whether a skill section already exists using a regex that matches across lines
$hasExistingSection = $existingContent -match [regex]::Escape($markerStart)

if ($hasExistingSection) {
    # Replace the entire section between (and including) the markers
    # Use a non-greedy match so only the first marker pair is replaced
    $pattern     = [regex]::Escape($markerStart) + '[\s\S]*?' + [regex]::Escape($markerEnd)
    $updatedContent = [regex]::Replace($existingContent, $pattern, $newSkillBlock)
    Write-Status '~' 'Replacing existing FORGE-SKILLS section'
} else {
    # Append the section at the end of the file, separated by a blank line
    $separator      = if ($existingContent.TrimEnd().Length -gt 0) { "`n`n" } else { '' }
    $updatedContent = $existingContent.TrimEnd() + $separator + $newSkillBlock + "`n"
    Write-Status '+' 'Appending new FORGE-SKILLS section (no existing section found)'
}

if ($DryRun) {
    Write-Status '~' '[DRY RUN] Would write copilot-instructions.md — skipping write' 'Yellow'
} else {
    Set-Content -Path $copilotInstructions -Value $updatedContent -Encoding UTF8 -NoNewline
    Write-Status '^' "Written: $copilotInstructions"
}

# ── Step 4: Write .aider/forge-system-prompt.md ───────────────────────────────

Write-SectionHeader 'Updating .aider/forge-system-prompt.md'

if (-not (Test-Path $aiderDir)) {
    if ($DryRun) {
        Write-Status '~' "[DRY RUN] Would create directory: $aiderDir" 'Yellow'
    } else {
        New-Item -ItemType Directory -Path $aiderDir -Force | Out-Null
        Write-Status '+' "Created directory: $aiderDir"
    }
}

$aiderLines = [System.Collections.Generic.List[string]]::new()
$aiderLines.Add('# Forge Workflow Skills — Aider System Prompt')
$aiderLines.Add('>')
$aiderLines.Add('> AUTO-GENERATED by scripts/sync-skills.ps1. Do NOT edit manually.')
$aiderLines.Add('> To use: aider --system-prompt .aider/forge-system-prompt.md')
$aiderLines.Add('> Or add `system-prompt: .aider/forge-system-prompt.md` to .aider.conf.yml')
$aiderLines.Add('>')
$aiderLines.Add("> Last synced: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') | Skills: $($skills.Count)")
$aiderLines.Add('')

foreach ($skill in $skills) {
    $aiderLines.Add('---')
    $aiderLines.Add('')
    $aiderLines.Add("## SKILL: $($skill.Name)")
    $aiderLines.Add('')
    $aiderLines.Add($skill.Content)
    $aiderLines.Add('')
}

$aiderLines.Add('---')

$aiderContent = $aiderLines -join "`n"

if ($DryRun) {
    Write-Status '~' '[DRY RUN] Would write .aider/forge-system-prompt.md — skipping write' 'Yellow'
} else {
    Set-Content -Path $aiderSystemPrompt -Value $aiderContent -Encoding UTF8 -NoNewline
    Write-Status '^' "Written: $aiderSystemPrompt"
}

# ── Step 5: Create/update .aider.conf.yml ────────────────────────────────────

Write-SectionHeader 'Ensuring .aider.conf.yml'

$aiderConf     = Join-Path $repoRoot '.aider.conf.yml'
$confEntry     = 'system-prompt: .aider/forge-system-prompt.md'

if (Test-Path $aiderConf) {
    $existingConf = Get-Content $aiderConf -Raw -Encoding UTF8
    if ($existingConf -match [regex]::Escape('system-prompt:')) {
        Write-Status '=' '.aider.conf.yml already has system-prompt entry — leaving unchanged'
    } else {
        if ($DryRun) {
            Write-Status '~' "[DRY RUN] Would append system-prompt entry to .aider.conf.yml" 'Yellow'
        } else {
            $updatedConf = $existingConf.TrimEnd() + "`n$confEntry`n"
            Set-Content -Path $aiderConf -Value $updatedConf -Encoding UTF8 -NoNewline
            Write-Status '+' "Appended system-prompt entry to existing .aider.conf.yml"
        }
    }
} else {
    if ($DryRun) {
        Write-Status '~' "[DRY RUN] Would create .aider.conf.yml" 'Yellow'
    } else {
        Set-Content -Path $aiderConf -Value "$confEntry`n" -Encoding UTF8 -NoNewline
        Write-Status '+' "Created .aider.conf.yml with system-prompt entry"
    }
}

# NOTE: There is intentionally NO global ~/.claude/commands push. Per-repo distribution
# (deploy-skills.ps1) is the single mechanism that gives each repo its skills, so a project only ever
# sees the skills appropriate to it — not forge-terminal's language-tuned set.

# ── Summary ───────────────────────────────────────────────────────────────────

Write-Host ''
Write-Host '─────────────────────────────────────────────' -ForegroundColor DarkGray
Write-Host ' Sync complete' -ForegroundColor Green -NoNewline
if ($DryRun) { Write-Host ' [DRY RUN — no files written]' -ForegroundColor Yellow } else { Write-Host '' }
Write-Host "  Skills embedded : $($skills.Count)" -ForegroundColor Gray
Write-Host "  Skill names     : $($skills | ForEach-Object { $_.Name } | Join-String -Separator ', ')" -ForegroundColor Gray
Write-Host "  Copilot target  : .github/copilot-instructions.md (forge-terminal only)" -ForegroundColor Gray
Write-Host "  Aider target    : .aider/forge-system-prompt.md (forge-terminal only)" -ForegroundColor Gray
Write-Host "  Aider config    : .aider.conf.yml" -ForegroundColor Gray
Write-Host '─────────────────────────────────────────────' -ForegroundColor DarkGray
Write-Host ''
Write-Host 'Next steps:' -ForegroundColor Cyan
Write-Host '  1. Review the diff: git diff .github/copilot-instructions.md'
Write-Host '  2. Commit: git add .github/copilot-instructions.md .aider/ .aider.conf.yml'
Write-Host '  3. To distribute skills to OTHER repos, run scripts/deploy-skills.ps1 (per-repo).'
Write-Host ''
