package main

// releaseScriptTemplate is the generic PowerShell release pipeline scaffolded into new
// projects by the Release Manager card. It handles Node.js and non-Node projects,
// accepts explicit version numbers or relative bump types, and merges to main before
// tagging so the release history always lives on the primary branch.
const releaseScriptTemplate = `# scripts/local-release.ps1
# Release pipeline — generated by Forge Terminal Release Manager
#
# Usage:
#   .\scripts\local-release.ps1 patch      # bug fix  (1.0.0 -> 1.0.1)
#   .\scripts\local-release.ps1 minor      # new feature (1.0.0 -> 1.1.0)
#   .\scripts\local-release.ps1 major      # breaking change (1.0.0 -> 2.0.0)
#   .\scripts\local-release.ps1 1.2.3      # explicit version (safe to re-run after any failure)
#   .\scripts\local-release.ps1 -DryRun    # preview without making changes
#
# Prerequisites: gh CLI authenticated (gh auth login), git with push access to origin

param(
    # Version bump type (major/minor/patch) or explicit semver string (e.g. '1.2.3').
    # Omit to re-publish the current version without changing it.
    [Parameter(Position = 0)]
    [string]$BumpType = '',

    # Preview mode — prints what would happen without making any changes.
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'

# ── Path constants ──────────────────────────────────────────────────────────────
$RepoRoot    = Split-Path -Parent $PSScriptRoot
$PackageJson = Join-Path $RepoRoot 'package.json'

# ── Version bump ────────────────────────────────────────────────────────────────
if ($BumpType -ne '') {
    Write-Host ''
    if ($BumpType -match '^\d+\.\d+\.\d+$') {
        # Explicit semver passed (e.g. '1.2.3') — set it directly without re-computing.
        # This prevents the double-bump bug: if a previous run partially updated package.json,
        # passing an explicit version is always safe via --allow-same-version.
        Write-Host "  Setting explicit version ($BumpType)..."
    } else {
        Write-Host "  Bumping version ($BumpType)..."
    }

    if (Test-Path $PackageJson) {
        Push-Location $RepoRoot
        try {
            # --no-git-tag-version: this script manages all git operations explicitly.
            # --allow-same-version: idempotent re-runs after partial failures never error.
            npm version $BumpType --no-git-tag-version --allow-same-version --silent
            if ($LASTEXITCODE -ne 0) { throw "npm version failed with exit code $LASTEXITCODE" }
        } finally {
            Pop-Location
        }
        Write-Host '  ✅ Version set'
    }
}

# ── Determine the git tag ───────────────────────────────────────────────────────
$GitTag = $null
if (Test-Path $PackageJson) {
    # Node.js project: read version from package.json (the authoritative source).
    $packageData    = Get-Content $PackageJson -Raw | ConvertFrom-Json
    $GitTag = "v$($packageData.version)"
} else {
    # Non-Node project: derive the version from git tags + bump type.
    $lastTag = git describe --tags --abbrev=0 2>$null
    if (-not $lastTag) { $lastTag = 'v0.0.0' }

    if ($BumpType -match '^\d+\.\d+\.\d+$') {
        $GitTag = "v$BumpType"
    } elseif ($BumpType -in @('patch','minor','major')) {
        $versionParts = $lastTag.TrimStart('v').Split('.')
        switch ($BumpType) {
            'patch' { $versionParts[2] = [int]$versionParts[2] + 1 }
            'minor' { $versionParts[1] = [int]$versionParts[1] + 1; $versionParts[2] = 0 }
            'major' { $versionParts[0] = [int]$versionParts[0] + 1; $versionParts[1] = 0; $versionParts[2] = 0 }
        }
        $GitTag = "v$($versionParts -join '.')"
    } else {
        $GitTag = $lastTag
    }
}

Write-Host ''
Write-Host "  ─────────────────────────────────────────────"
Write-Host "  Release: $GitTag"
Write-Host "  ─────────────────────────────────────────────"

if ($DryRun) {
    Write-Host '  [DRY RUN] No changes made.' -ForegroundColor Yellow
    exit 0
}

# ── Build steps (customize for your project) ───────────────────────────────────
# Uncomment whichever build commands apply to your project and remove the others.
# Push-Location $RepoRoot
# npm run build
# go build -o dist/myapp .
# Pop-Location

# ── Release assets (customize for your project) ────────────────────────────────
# List the file paths (relative to $RepoRoot) to attach to the GitHub Release.
# Leave the array empty for a source-only release.
$ReleaseAssets = @(
    # 'dist\myapp.exe',
    # 'dist\myapp.zip',
)

# ── Git: commit → merge to main → tag → publish ────────────────────────────────
$originalBranch = git branch --show-current 2>$null

# Commit version bump if we changed something (the add is harmless if nothing changed).
if ($BumpType -ne '') {
    git add -A
    git commit -m "chore: bump version to $GitTag"
    git push origin HEAD
    if ($LASTEXITCODE -ne 0) { throw "Failed to push version bump to origin" }
}

# Merge to main so the release tag lives on the primary branch.
# git describe then returns the correct version from any branch after the release.
Write-Host "  Merging '$originalBranch' → main..."
git checkout main
if ($LASTEXITCODE -ne 0) { throw "git checkout main failed — ensure main exists" }
git pull origin main
git merge $originalBranch --no-edit
if ($LASTEXITCODE -ne 0) { throw "git merge $originalBranch failed — resolve conflicts then re-run" }
git push origin main
if ($LASTEXITCODE -ne 0) { throw "Failed to push main — check push permissions" }
Write-Host '  ✅ Merged and pushed to main'

# Remove stale local tag. Guard with git tag -l first — attempting to delete a
# non-existent tag under ErrorActionPreference=Stop throws NativeCommandError.
$existingLocalTag = git tag -l $GitTag 2>$null
if ($existingLocalTag) {
    git tag -d $GitTag | Out-Null
}

# Delete stale remote tag and release so this step is idempotent (safe to re-run).
git push origin ":refs/tags/$GitTag" 2>&1 | Out-Null
$staleRelease = gh release view $GitTag 2>&1
if ($LASTEXITCODE -eq 0) {
    gh release delete $GitTag --yes 2>&1 | Out-Null
}

# Create the tag on main HEAD and push it.
git tag $GitTag
git push origin $GitTag
if ($LASTEXITCODE -ne 0) { throw "Failed to push tag $GitTag" }

# Return to the original branch so the developer workspace is unchanged.
git checkout $originalBranch 2>&1 | Out-Null

# ── GitHub Release ─────────────────────────────────────────────────────────────
if ($ReleaseAssets.Count -gt 0) {
    $AssetPaths = $ReleaseAssets | ForEach-Object { Join-Path $RepoRoot $_ }
    gh release create $GitTag @AssetPaths --title $GitTag --generate-notes --latest
} else {
    gh release create $GitTag --title $GitTag --generate-notes --latest
}

Write-Host ''
$repoSlug = gh repo view --json nameWithOwner -q .nameWithOwner 2>$null
Write-Host "  ✅ Released $GitTag" -ForegroundColor Green
if ($repoSlug) {
    Write-Host "     https://github.com/$repoSlug/releases/tag/$GitTag" -ForegroundColor Cyan
}
`
