/**
 * AgentBlock - Markdown rendering cell for AI planning/reasoning
 * 
 * Displays AI-generated content in a rich markdown format.
 * Used for:
 * - AI explanations and reasoning
 * - Planning steps generated by the SLM Router
 * - Code explanations with syntax highlighting
 */

import React, { useState, useCallback, useMemo } from 'react';
import { Bot, Copy, Check, ChevronDown, ChevronUp, Sparkles, RefreshCw } from 'lucide-react';

// Block types for different AI output
const AGENT_TYPE = {
  PLAN: 'plan',
  EXPLANATION: 'explanation', 
  CODE_REVIEW: 'code_review',
  ERROR_ANALYSIS: 'error_analysis',
  THINKING: 'thinking',
};

const AgentBlock = ({
  cellId,
  content = '',
  agentType = AGENT_TYPE.EXPLANATION,
  model = 'AI',
  timestamp,
  isStreaming = false,
  onRegenerate,
  onCopy,
}) => {
  const [isCollapsed, setIsCollapsed] = useState(false);
  const [copied, setCopied] = useState(false);

  // Get icon and label based on agent type
  const { icon: TypeIcon, label, color } = useMemo(() => {
    switch (agentType) {
      case AGENT_TYPE.PLAN:
        return { icon: Sparkles, label: 'Plan', color: 'var(--accent-purple)' };
      case AGENT_TYPE.CODE_REVIEW:
        return { icon: Bot, label: 'Code Review', color: 'var(--accent-green)' };
      case AGENT_TYPE.ERROR_ANALYSIS:
        return { icon: Bot, label: 'Error Analysis', color: 'var(--accent-red)' };
      case AGENT_TYPE.THINKING:
        return { icon: Sparkles, label: 'Thinking...', color: 'var(--accent-yellow)' };
      default:
        return { icon: Bot, label: 'AI', color: 'var(--accent-blue)' };
    }
  }, [agentType]);

  // Copy content to clipboard
  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    onCopy?.(content);
    setTimeout(() => setCopied(false), 2000);
  }, [content, onCopy]);

  // Parse markdown content
  const parsedContent = useMemo(() => {
    return parseMarkdown(content);
  }, [content]);

  return (
    <div className={`agent-block ${agentType} ${isStreaming ? 'streaming' : ''}`}>
      {/* Header */}
      <div className="agent-block-header">
        <div className="agent-block-title">
          <TypeIcon size={16} style={{ color }} />
          <span className="agent-block-label">{label}</span>
          {model && <span className="agent-block-model">{model}</span>}
          {timestamp && (
            <span className="agent-block-time">
              {new Date(timestamp).toLocaleTimeString()}
            </span>
          )}
        </div>
        
        <div className="agent-block-actions">
          {onRegenerate && (
            <button 
              className="agent-block-btn regenerate"
              onClick={onRegenerate}
              title="Regenerate"
              disabled={isStreaming}
            >
              <RefreshCw size={14} className={isStreaming ? 'spinning' : ''} />
            </button>
          )}
          
          <button 
            className="agent-block-btn copy"
            onClick={handleCopy}
            title="Copy"
          >
            {copied ? <Check size={14} /> : <Copy size={14} />}
          </button>
          
          <button 
            className="agent-block-btn collapse"
            onClick={() => setIsCollapsed(!isCollapsed)}
            title={isCollapsed ? 'Expand' : 'Collapse'}
          >
            {isCollapsed ? <ChevronDown size={14} /> : <ChevronUp size={14} />}
          </button>
        </div>
      </div>

      {/* Content */}
      {!isCollapsed && (
        <div className="agent-block-content">
          {parsedContent}
          {isStreaming && <span className="streaming-cursor">▊</span>}
        </div>
      )}
    </div>
  );
};

/**
 * Parse markdown to React elements
 * Handles: headers, code blocks, lists, inline code, bold, italic
 */
function parseMarkdown(text) {
  if (!text) return null;
  
  const lines = text.split('\n');
  const elements = [];
  let inCodeBlock = false;
  let codeBlockContent = '';
  let codeLanguage = '';

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    // Code block handling
    if (trimmed.startsWith('```')) {
      if (!inCodeBlock) {
        inCodeBlock = true;
        codeLanguage = trimmed.slice(3).trim();
        codeBlockContent = '';
      } else {
        elements.push(
          <pre key={`code-${i}`} className="agent-code-block">
            {codeLanguage && <div className="code-lang">{codeLanguage}</div>}
            <code>{codeBlockContent}</code>
          </pre>
        );
        inCodeBlock = false;
        codeBlockContent = '';
        codeLanguage = '';
      }
      continue;
    }

    if (inCodeBlock) {
      codeBlockContent += line + '\n';
      continue;
    }

    // Headers
    if (trimmed.startsWith('### ')) {
      elements.push(<h4 key={`h4-${i}`} className="agent-heading">{trimmed.slice(4)}</h4>);
    } else if (trimmed.startsWith('## ')) {
      elements.push(<h3 key={`h3-${i}`} className="agent-heading">{trimmed.slice(3)}</h3>);
    } else if (trimmed.startsWith('# ')) {
      elements.push(<h2 key={`h2-${i}`} className="agent-heading">{trimmed.slice(2)}</h2>);
    }
    // Lists
    else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      elements.push(
        <li key={`li-${i}`} className="agent-list-item">
          {parseInline(trimmed.slice(2))}
        </li>
      );
    }
    // Numbered lists
    else if (/^\d+\.\s/.test(trimmed)) {
      const match = trimmed.match(/^\d+\.\s(.*)$/);
      if (match) {
        elements.push(
          <li key={`oli-${i}`} className="agent-list-item ordered">
            {parseInline(match[1])}
          </li>
        );
      }
    }
    // Regular paragraphs
    else if (trimmed) {
      elements.push(
        <p key={`p-${i}`} className="agent-paragraph">
          {parseInline(line)}
        </p>
      );
    }
  }

  // Handle unclosed code block
  if (inCodeBlock) {
    elements.push(
      <pre key="code-final" className="agent-code-block">
        {codeLanguage && <div className="code-lang">{codeLanguage}</div>}
        <code>{codeBlockContent}</code>
      </pre>
    );
  }

  return elements;
}

/**
 * Parse inline markdown (bold, italic, inline code)
 */
function parseInline(text) {
  if (!text) return text;
  
  const parts = [];
  let key = 0;

  // For simplicity, just handle inline code for now
  const inlineCodeRegex = /`([^`]+)`/g;
  let lastIndex = 0;
  let match;

  while ((match = inlineCodeRegex.exec(text)) !== null) {
    if (match.index > lastIndex) {
      parts.push(text.slice(lastIndex, match.index));
    }
    parts.push(<code key={key++} className="inline-code">{match[1]}</code>);
    lastIndex = match.index + match[0].length;
  }

  if (lastIndex < text.length) {
    parts.push(text.slice(lastIndex));
  }

  return parts.length > 0 ? parts : text;
}

export { AgentBlock, AGENT_TYPE };
export default AgentBlock;
